=== feventurini/SensorLibrary/src/stationSchema.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" 
	xmlns="http://www.w3schools.com"
	targetNamespace="http://www.w3schools.com"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="station"> <!-- il nome della station -->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="provider">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="IPv4Address" name="ip" use="required" />
								<xs:attribute type="xs:nonNegativeInteger" name="port"
									use="optional" default="1099" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="sensor" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" /> <!-- il nome del sensore nella station -->
							<xs:element type="xs:string" name="parameters" /> <!-- il file da cui caricare i parametri per questo sensore -->
							<xs:element type="xs:boolean" name="loadAtStartup" /> <!-- se la station deve avviare questo sensore all'accensione -->
						</xs:sequence>
						<xs:attribute type="xs:string" name="class" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="IPv4Address">
		<xs:annotation>
			<xs:documentation>
				IPv4 address in the dotted-decimal notation.
			</xs:documentation>
		</xs:annotation>

		<xs:restriction base="xs:string">
			<xs:pattern
				value="((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

<!-- Per semplicità di gestione nessun attributo relativo ai sensori è opzionale -->
<!-- Scelto come attributo di sensor il nome della classe. -->
<!-- Scelte invece come elementi di sensor le informazioni utili alla creazione 
	di una particolare istanza di un sensore all'interno della station -->

=== feventurini/SensorLibrary/src/station.xml
<?xml version="1.0" encoding="UTF-8"?>
<station name="cucina" xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com stationSchema.xsd">
	<provider ip="192.168.0.12" port="1099"/>
	<sensor class="sensor.implementations.Rfid_SL038">
		<name>rfidFrigo</name>
		<parameters>rfid.properties</parameters>
		<loadAtStartup>false</loadAtStartup>
	</sensor>
	<sensor class="sensor.implementations.Temp4000">
		<name>tempForno</name>
		<parameters>rfid.properties</parameters>
		<loadAtStartup>true</loadAtStartup>
	</sensor>
	<sensor class="sensor.implementations.Temp4000">
		<name>rfidAmbiente</name>
		<parameters>rfid.properties</parameters>
		<loadAtStartup>true</loadAtStartup>
	</sensor>
</station>

=== feventurini/SensorLibrary/src/mockstation.xml
<?xml version="1.0" encoding="UTF-8"?>
<station name="cucina" xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com stationSchema.xsd">
	
	<provider ip="192.168.0.12" port="1099"/>
	
	<sensor class="sensor.implementations.Rfid_SL030">
		<name>rfid</name>
		<parameters>rfid.properties</parameters>
		<loadAtStartup>true</loadAtStartup>
	</sensor>
	<sensor class="sensor.implementations.TempAndHumiditySensor">
		<name>temp</name>
		<parameters>TempAndHumiditySensor.properties</parameters>
		<loadAtStartup>true</loadAtStartup>
	</sensor>
	<sensor class="sensor.implementations.GroveRgbDisplay">
		<name>display</name>
		<parameters></parameters>
		<loadAtStartup>true</loadAtStartup>
	</sensor>
</station>

=== feventurini/SensorLibrary/src/cucinastation.xml
<?xml version="1.0" encoding="UTF-8"?>
<station name="cucina" xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com stationSchema.xsd">
	
	<provider ip="192.168.0.12" port="1099"/>
	
	<sensor loadAtStartup="true">
		<name>rfidFrigo</name>
		<class>sensor.implementations.Rfid_SL030</class>
		<parameters>rfid.properties</parameters>
	</sensor>
	<sensor loadAtStartup="true">
		<name>tempAmbiente</name>
		<class>sensor.implementations.TempAndHumiditySensor</class>
		<parameters>TempAndHumiditySensor.properties</parameters>
	</sensor>
	<sensor loadAtStartup="true">
		<name>display</name>
		<class>sensor.implementations.GroveRgbDisplay</class>
		<parameters></parameters>
	</sensor>
</station>

=== feventurini/SensorLibrary/assets/weatherstation.xml
<?xml version="1.0" encoding="UTF-8"?>
<station name="balcone" xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com stationSchema.xsd">
	
	<provider ip="192.168.0.12" port="1099"/>
	
	<sensor loadAtStartup="false">
		<name>tempFuori</name>
		<class>sensor.implementations.TempAndHumiditySensor</class>
		<parameters>assets/TempAndHumiditySensor.properties</parameters>
	</sensor>
	<sensor loadAtStartup="true">
		<name>meteo</name>
		<class>sensor.implementations.Wunderground</class>
		<parameters>assets/Wunderground.properties</parameters>
	</sensor>
	<sensor loadAtStartup="false">
		<name>display</name>
		<class>sensor.implementations.GroveRgbDisplay</class>
		<parameters></parameters>
	</sensor>
</station>
